class zh_cn:
    def __init__(self):
        self.ErrorRetrievingConfig = "获取配置失败"
        self.launch = "启动AppleID_Auto"
        self.failOnPasswordUpdate = "更新密码失败"
        self.failOnRetrievingPassword = "获取密码失败"
        self.failOnMessageUpdate = "更新消息失败"
        self.failOnReportingProxyError = "上报代理错误失败"
        self.failOnRetrievingProxyFromAPI = "从API获取代理失败"
        self.retrievedProxyFromAPI = "从API获取到代理"
        self.backgroundRunning = "已启用 后台运行"
        self.removeDevice = "已启用 删除设备"
        self.checkPassword = "已启用 检查密码"
        self.autoUpdatePassword = "已启用 定时更新密码"
        self.usingProxyID = "使用代理ID"
        self.failOnRefreshingPage = "刷新页面失败"
        self.proxyEnabledRefreshing = "已启用代理，请检查代理是否可用"
        self.proxyEnabledRefreshingAPI = "页面加载失败，可能是代理不可用"
        self.failOnLoadingPage = "页面加载失败"
        self.IPBlocked = "页面加载失败，疑似服务器IP被封禁"
        self.seeLog = "页面加载失败，具体原因请查看日志"
        self.failOnGettingCaptcha = "无法获取验证码"
        self.failOnRetrievingPage = "无法获取页面内容，即将退出程序"
        self.proxyEnabledGettingContent = "无法获取页面内容，可能是代理不可用"
        self.failOnGettingPage = "无法获取页面内容"
        self.captchaCorrect = "验证码正确"
        self.captchaFail = "验证码错误，重新输入"
        self.login = "登录成功"
        self.blocked = "无法处理请求，可能是账号失效或服务器IP被拉黑"
        self.loginFailCheckLog = "解锁登录失败，可能是账号失效或服务器IP被拉黑，具体请查看后端日志"


class en_us:
    def __init__(self):
        self.ErrorRetrievingConfig = "Error retrieving config"
        self.launch = "Launch AppleID_Auto"
        self.failOnPasswordUpdate = "Password update failed"
        self.failOnRetrievingPassword = "Retrieving password failed"
        self.failOnMessageUpdate = "Message update failed"
        self.failOnReportingProxyError = "Reporting proxy error failed"
        self.failOnRetrievingProxyFromAPI = "Retrieving proxy from API failed"
        self.retrievedProxyFromAPI = "Retrieved proxy from API"
        self.backgroundRunning = "Background running enabled"
        self.removeDevice = "Remove device enabled"
        self.checkPassword = "Check password enabled"
        self.autoUpdatePassword = "Auto update password enabled"
        self.UsingProxyID = "Using proxy ID"
        self.failOnRefreshingPage = "Refreshing page failed"
        self.proxyEnabledRefreshing = "Proxy is enabled, please check the availability of proxy"
        self.proxyEnabledRefreshingAPI = "Page loading failed, proxy may not be available"
        self.failOnLoadingPage = "Page loading failed"
        self.IPBlocked = "Page loading failed, the server IP may be blocked"
        self.seeLog = "Page loading failed, please check the log for details"
        self.failOnGettingCaptcha = "Failed to get captcha"
        self.failOnRetrievingPage = "Failed to retrieve page content, exiting"
        self.proxyEnabledGettingContent = "Failed to retrieve page content, proxy may not be available"
        self.failOnGettingPage = "Failed to retrieve page content"
        self.captchaCorrect = "Captcha correct"
        self.captchaFail = "Captcha incorrect, please try again"
        self.login = "Login successful"
        self.blocked = "Unable to process request, account may be invalid or server IP may be blocked"
        self.loginFailCheckLog = "Login failed, account may be invalid or server IP may be blocked, " \
                                 "please check the backend log for details"
